title: Annegrete
description: Personal website and blog
url: "https://annegretepeek.github.io"
baseurl: "/annegrete.ee"

markdown: kramdown
permalink: /blog/:year/:month/:title/

plugins:
  - jekyll-feed